### ISSUE TITLE
 Opening a PiP window requires https or file protocol

### ISSUE THREAD

**Issue by GoodluckH** [dlitsman/document-pip#1]
Pretty cool tutorial.

Was wondering if you encountered the "Opening a PiP window requires https or file protocol" error on development mode?

<img width="552" alt="Screenshot 2023-12-10 at 6 51 27 PM" src="https://github.com/dlitsman/document-pip/assets/23110002/91714968-ff6f-4e88-933f-8981272f4e78">

**Comment by contigen** [comment]
Hi! Apparently, it's a bug from the API implementation itself. Run your dev server in https mode, Next.js / Nuxt supports it, and there's also a Vite plugin;  otherwise, you might want to consider utilising `mkcert`
